// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Reservation struct {
	ID              uuid.UUID
	ReservationDate time.Time
	ReservationTime int32
	Email           string
	Pin             string
	MachineNum      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
