// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	GetReservationByEmail(ctx context.Context, email string) (Reservation, error)
	ListReservations(ctx context.Context) ([]Reservation, error)
}

var _ Querier = (*Queries)(nil)
