// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservation (
    id,
    reservation_date,
    reservation_time,
    email,
    pin,
    machine_num,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, reservation_date, reservation_time, email, pin, machine_num, created_at, updated_at
`

type CreateReservationParams struct {
	ID              uuid.UUID
	ReservationDate time.Time
	ReservationTime int32
	Email           string
	Pin             string
	MachineNum      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation,
		arg.ID,
		arg.ReservationDate,
		arg.ReservationTime,
		arg.Email,
		arg.Pin,
		arg.MachineNum,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.Email,
		&i.Pin,
		&i.MachineNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, reservation_date, reservation_time, email, pin, machine_num, created_at, updated_at FROM reservation WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.Email,
		&i.Pin,
		&i.MachineNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReservations = `-- name: ListReservations :many
SELECT id, reservation_date, reservation_time, email, pin, machine_num, created_at, updated_at FROM reservation ORDER BY reservation_date
`

func (q *Queries) ListReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationDate,
			&i.ReservationTime,
			&i.Email,
			&i.Pin,
			&i.MachineNum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
