// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	GetReservation(ctx context.Context, id uuid.UUID) (Reservation, error)
	ListReservations(ctx context.Context) ([]Reservation, error)
}

var _ Querier = (*Queries)(nil)
